services:
  usercurd:
    build: .
    container_name: usercurd
    ports:
      - '8080:8080'
    volumes:
      - ./src/main/resources/application.properties:/usr/src/app/application.properties
      - ./.env:/usr/src/app/.env
    environment:
      SPRING_CONFIG_LOCATION: file:/usr/src/app/application.properties
      SPRING_DATASOURCE_URL: jdbc:mysql://dbusercurd:3306/${DB_NAME}
    env_file:
      - ./.env
    depends_on:
      dbusercurd:
        condition: service_healthy
    networks:
      - usercurdnetwork

  dbusercurd:
    image: mysql/mysql-server
    container_name: dbusercurd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbusercurd-data:/var/lib/mysql
    ports:
      - '3307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - usercurdnetwork

volumes:
  dbusercurd-data:

networks:
  usercurdnetwork:
    driver: bridge
